import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Main from '../component/Main';
import Post from '../component/Post';
import Reviews from '../component/Reviews';
import Contact from '../component/Contact';

export default function Home() {
  return (
    <div className={styles.App}>
      <Head>
        <title>Jacket Star</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Jacket Star" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>

      <Main />
      <Post></Post>
      <Reviews></Reviews>
      <Contact></Contact>

    </div>
  )
}
